### ISSUE TITLE
App doesn't use full screen in iPhone Retina 4 inch

### ISSUE THREAD

**Issue by vskr** [acani/Chats#19]
App doesn't use full height when installed on a 4 inch retina phones. It only uses ~80% in the center, rest of the top and bottom layers are black

I tried     self.view.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;

It still doesn't work. Was anyone able to get it to work properly (use full height)

**Comment by mattdipasquale** [comment]
Fixed
