### ISSUE TITLE
Installation Guide Client & Server

### ISSUE THREAD

**Issue by deada92** [acani/Chats#24]
Hello i m new to iOS, not really new but not a senior too^^ I found Acani and it seems to be what i need. I m developing a messaging app and i was trrying to install Acani. The project is starting but immeditly after a 404 error comes up.

I installed Node.js, ws and jitsu.. I registered also myself at nodejitsu.. whats the next step?

Is there a step by step guide?

**Comment by mattdipasquale** [comment]
No, I removed the server because it wasn't ready. Sorry.
