### ISSUE TITLE
Chats/MessageBubbleCell.swift:89:31:    Extra argument 'scale' in call

### ISSUE THREAD

**Issue by josuerp** [acani/Chats#43]
Hi

i' can't  make work the Chats application
the error is the next:  Chats/MessageBubbleCell.swift:89:31:    Extra argument 'scale' in call

what could  be the problem??

thanks in advance.

https://www.dropbox.com/s/xi40vybp246jnap/Captura%20de%20pantalla%202014-10-30%2017.29.51.png?dl=0

https://www.dropbox.com/s/zx3z11tlwkzp6pl/Captura%20de%20pantalla%202014-10-30%2017.30.05.png?dl=0

![image](https://cloud.githubusercontent.com/assets/8657893/4854139/06930de8-608e-11e4-84d8-f47e04cb0b4a.png)

**Comment by mattdipasquale** [comment]
I'm not sure, but it works fine now with the latest version of Xcode.
