### ISSUE TITLE
error occurs when I copy try to paste copied message into textbox

### ISSUE THREAD

**Issue by wuichen** [acani/Chats#44]
When I copy a message and try to paste it into textbox, error occurs

![screen shot 2015-02-08 at 12 32 17 am](https://cloud.githubusercontent.com/assets/6353587/6095928/015d646e-af2a-11e4-87c1-36e212dac134.png)
![screen shot 2015-02-08 at 12 32 28 am](https://cloud.githubusercontent.com/assets/6353587/6095929/0160fc50-af2a-11e4-934c-ccaaec1ce44d.png)

**Comment by mattdipasquale** [comment]
Fixed. Thanks! :-)
