### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by kazuminn** [acani/Chats#53]
This repositry only occur error

<pry>
$ git clone --recursive git@github.com:acani/Chats.git
Cloning into 'Chats'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
<pry>

why?

**Comment by mattdipasquale** [comment]
Do you have the latest version of Git? Does this answer solve your issue?
http://stackoverflow.com/a/25124246/242933

**Comment by mattdipasquale** [comment]
How about this? http://stackoverflow.com/questions/25957125/git-submodule-permission-denied

**Comment by mattdipasquale** [comment]
I posted a question about this because others have reported this issue before. http://stackoverflow.com/questions/31184930/how-to-use-ssh-instead-of-http-for-git-submodules

A quick & dirty fix is to just outright git clone all of the submodules into the correct directories.

**Comment by mattdipasquale** [comment]
I think I fixed this by replacing in the submodule URLs `git@github.com:` with `git://github.com/`.
