### ISSUE TITLE
When I pull the code with git , some files missing

### ISSUE THREAD

**Issue by MrMarik** [acani/Chats#55]
Hi，I`m a iOS  developer from china，when i use ‘git clone https://github.com/acani/Chats-iPhone-Client.git' to pull the code from git, I find that the swift files under 'CodeInputView' & 'Networking' were missing, so i can't run the project, is there anything wrong?

**Comment by mattdipasquale** [comment]
Yes, remove the repository, and clone it recursively, like this:

    git clone --recursive git@github.com:acani/Chats-iPhone-Client.git

> --recursive
> --recurse-submodules
> After the clone is created, initialize all submodules within, using their default settings. This is equivalent to running git submodule update --init --recursive immediately after the clone is finished. This option is ignored if the cloned repository does not have a worktree/checkout (i.e. if any of --no-checkout/-n, --bare, or --mirror is given)

Source: https://git-scm.com/docs/git-clone

See also: https://github.com/acani/Chats/blob/master/README.md
