### ISSUE TITLE
Can not run on iphone 6 with iOS 9.3

### ISSUE THREAD

**Issue by ishell** [acani/Chats#57]
error : `dyld: Library not loaded: @rpath/Alerts.framework/Alerts
  Referenced from: /var/containers/Bundle/Application/7F850C82-20D2-44B2-BBB2-79907A42A821/Chats.app/Chats
  Reason: image not found`

**Comment by mattdipasquale** [comment]
Did you fall the instructions in the README, cloning "this project and its submodules with `git clone --recursive`"?

**Comment by mattdipasquale** [comment]
http://bfy.tw/5iBF
