### ISSUE TITLE
resignFirstResponder on chatInput clears the tableView

### ISSUE THREAD

**Issue by YDing** [acani/Chats#8]
It'd be nice to have the capability to hide the keyboard upon sending the message.  Therefore, I added [chatInput resignFirstResponder] to the sendMessage method.  However, invoking this function call seems to clear the entire view of chats.  The screen just becomes empty when the button is pressed.

**Comment by mattdipasquale** [comment]
I'm closing this issue because I think the keyboard should stay up after your send a message, just like it does in the native iPhone Messages app.
